// Lines of business translations by locale
// Sourced from messages/{locale}/auth.json -> register_form.portfolio.lines_of_business
const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    accident_health: 'Accident & Health',
    aviation: 'Aviation',
    bloodstock: 'Bloodstock',
    casualty: 'Casualty',
    construction: 'Construction',
    cyber: 'Cyber',
    energy: 'Energy',
    event_cancellation: 'Event Cancellation',
    fine_art_specie: 'Fine Art & Specie',
    legal_expenses: 'Legal Expenses',
    life: 'Life',
    livestock: 'Livestock',
    marine: 'Marine',
    management_liability: 'Management Liability (D&O, EPLI etc)',
    motor_commercial: 'Motor, commercial',
    motor_personal: 'Motor, personal lines',
    pet: 'Pet',
    political_risk: 'Political Risk',
    professional_indemnity: 'Professional Indemnity / E&O',
    property_commercial: 'Property, commercial',
    property_personal: 'Property, personal lines',
    surety: 'Surety',
    trade_credit: 'Trade Credit',
    travel: 'Travel',
    warranty_indemnity: 'Warranty & Indemnity',
    other: 'Other',
    other_2: 'Other #2',
    other_3: 'Other #3',
  },
  de: {
    accident_health: 'Unfall & Gesundheit',
    aviation: 'Luftfahrt',
    bloodstock: 'Viehversicherung',
    casualty: 'Haftpflicht',
    construction: 'Bau',
    cyber: 'Cyber',
    energy: 'Energie',
    event_cancellation: 'Veranstaltungsausfall',
    fine_art_specie: 'Kunstgegenstände & Wertgegenstände',
    legal_expenses: 'Rechtsschutz',
    life: 'Leben',
    livestock: 'Vieh',
    marine: 'Transport',
    management_liability: 'Management-Haftpflicht (D&O, EPLI etc)',
    motor_commercial: 'Kfz, gewerblich',
    motor_personal: 'Kfz, privat',
    pet: 'Haustier',
    political_risk: 'Politisches Risiko',
    professional_indemnity: 'Berufshaftpflicht / E&O',
    property_commercial: 'Sachversicherung, gewerblich',
    property_personal: 'Sachversicherung, privat',
    surety: 'Bürgschaft',
    trade_credit: 'Kreditversicherung',
    travel: 'Reise',
    warranty_indemnity: 'Garantie & Schadloshaltung',
    other: 'Sonstiges',
    other_2: 'Sonstiges #2',
    other_3: 'Sonstiges #3',
  },
  fr: {
    accident_health: 'Accident et Santé',
    aviation: 'Aviation',
    bloodstock: 'Cheptel de Pur-sang',
    casualty: 'Responsabilité Civile',
    construction: 'Construction',
    cyber: 'Cyber',
    energy: 'Énergie',
    event_cancellation: "Annulation d'Événements",
    fine_art_specie: 'Beaux-Arts et Espèces',
    legal_expenses: 'Frais Juridiques',
    life: 'Vie',
    livestock: 'Bétail',
    marine: 'Maritime',
    management_liability: 'Responsabilité de Direction (D&O, EPLI etc)',
    motor_commercial: 'Automobile, commercial',
    motor_personal: 'Automobile, particuliers',
    pet: 'Animaux de Compagnie',
    political_risk: 'Risque Politique',
    professional_indemnity: 'Responsabilité Professionnelle / E&O',
    property_commercial: 'Biens, commercial',
    property_personal: 'Biens, particuliers',
    surety: 'Caution',
    trade_credit: 'Crédit Commercial',
    travel: 'Voyage',
    warranty_indemnity: 'Garantie et Indemnité',
    other: 'Autre',
    other_2: 'Autre #2',
    other_3: 'Autre #3',
  },
  es: {
    accident_health: 'Accidentes y Salud',
    aviation: 'Aviación',
    bloodstock: 'Ganado',
    casualty: 'Responsabilidad Civil',
    construction: 'Construcción',
    cyber: 'Cibernético',
    energy: 'Energía',
    event_cancellation: 'Cancelación de Eventos',
    fine_art_specie: 'Bellas Artes y Especies',
    legal_expenses: 'Gastos Legales',
    life: 'Vida',
    livestock: 'Ganado Vivo',
    marine: 'Marítimo',
    management_liability: 'Responsabilidad de Gestión (D&O, EPLI etc)',
    motor_commercial: 'Motor, comercial',
    motor_personal: 'Motor, líneas personales',
    pet: 'Mascotas',
    political_risk: 'Riesgo Político',
    professional_indemnity: 'Indemnización Profesional / E&O',
    property_commercial: 'Propiedad, comercial',
    property_personal: 'Propiedad, líneas personales',
    surety: 'Fianza',
    trade_credit: 'Crédito Comercial',
    travel: 'Viajes',
    warranty_indemnity: 'Garantía e Indemnización',
    other: 'Otro',
    other_2: 'Otro #2',
    other_3: 'Otro #3',
  },
  it: {
    accident_health: 'Infortuni e Salute',
    aviation: 'Aviazione',
    bloodstock: 'Bestiame da Riproduzione',
    casualty: 'Responsabilità Civile',
    construction: 'Costruzioni',
    cyber: 'Cyber',
    energy: 'Energia',
    event_cancellation: 'Cancellazione Eventi',
    fine_art_specie: 'Belle Arti e Valori',
    legal_expenses: 'Spese Legali',
    life: 'Vita',
    livestock: 'Bestiame',
    marine: 'Marittimo',
    management_liability: 'Responsabilità Gestionale (D&O, EPLI ecc)',
    motor_commercial: 'Motor, commerciale',
    motor_personal: 'Motor, linee personali',
    pet: 'Animali Domestici',
    political_risk: 'Rischio Politico',
    professional_indemnity: 'Indennizzo Professionale / E&O',
    property_commercial: 'Proprietà, commerciale',
    property_personal: 'Proprietà, linee personali',
    surety: 'Fideiussioni',
    trade_credit: 'Credito Commerciale',
    travel: 'Viaggi',
    warranty_indemnity: 'Garanzia e Indennizzo',
    other: 'Altro',
    other_2: 'Altro #2',
    other_3: 'Altro #3',
  },
  nl: {
    accident_health: 'Ongevallen & Gezondheid',
    aviation: 'Luchtvaart',
    bloodstock: 'Veestapel',
    casualty: 'Aansprakelijkheid',
    construction: 'Bouw',
    cyber: 'Cyber',
    energy: 'Energie',
    event_cancellation: 'Evenementannulering',
    fine_art_specie: 'Kunst & Waardevolle Voorwerpen',
    legal_expenses: 'Rechtsbijstand',
    life: 'Leven',
    livestock: 'Vee',
    marine: 'Scheepvaart',
    management_liability: 'Bestuurdersaansprakelijkheid (D&O, EPLI etc)',
    motor_commercial: 'Motor, commercieel',
    motor_personal: 'Motor, particulier',
    pet: 'Huisdier',
    political_risk: 'Politiek Risiko',
    professional_indemnity: 'Beroepsaansprakelijkheid / E&O',
    property_commercial: 'Eigendom, commercieel',
    property_personal: 'Eigendom, particulier',
    surety: 'Borgstelling',
    trade_credit: 'Handelskredieten',
    travel: 'Reizen',
    warranty_indemnity: 'Garantie & Vrijwaring',
    other: 'Andere',
    other_2: 'Andere #2',
    other_3: 'Andere #3',
  },
};

// Convert a key to display name for the given locale
export function getLineOfBusinessDisplay(key: string, locale: string = 'en'): string {
  const translations = TRANSLATIONS[locale] || TRANSLATIONS.en;
  return translations[key] || TRANSLATIONS.en[key] || key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}
